### ISSUE TITLE
No signup option

### ISSUE THREAD

**Issue by ashwath2767** [signalfire/property-rails#1]
How do we login or create a admin account from view?? 
No signup option?

**Comment by etewiah** [comment]
Ha ha - good point ;)
I think this project has been abandoned.  I tried getting in touch with the creator last year without success.
I have since launched my own project which is actively maintained. You are welcome to try it out.  I'll do my best to resolve any issues you encounter with it:

https://github.com/etewiah/property_web_builder

**Comment by signalfire** [comment]
The project is stated as a "work in progress". As with most open-source projects If you need to add a registration form or any other functionality fork the project to add it yourself.
